/**
 * Generate a TypeScript types file from a ledric DescribeModelResult.
 * Pure function — no I/O, easy to unit-test. Consumed by the
 * `ledric types` CLI command which handles fetching the schema and
 * writing the file.
 */

import type { DescribeModelResult, TypeDescription } from '@ledric/core';
import type { FieldDef } from '@ledric/schema';

export interface CodegenOptions {
  /** Header banner. Default: a generated-by notice. */
  header?: string;
  /**
   * When true, the file `declare module '@ledric/sdk'`-augments the
   * Entries map onto the SDK so `client.read<'blog_post'>('hello')`
   * picks up the right interface. Default: false (keeps the file
   * standalone).
   */
  augmentSdk?: boolean;
}

export function generateTypes(
  model: DescribeModelResult,
  opts: CodegenOptions = {}
): string {
  const lines: string[] = [];
  const banner =
    opts.header ??
    `// Generated by \`ledric types\` — do not edit by hand.\n// Schema version: ${model.schema_version}\n// Re-run after any \`create_type\` / \`alter_type\` to keep in sync.`;
  lines.push(banner, '');

  // Branded primitives — encode the wire-shape distinction in the type
  // system so an asset id can never be passed where a slug is wanted.
  lines.push(
    `export type AssetId = string & { readonly __asset: unique symbol };`,
    `export type EntryRef<T extends string = string> = \`\${T}/\${string}\` & { readonly __ref: unique symbol };`,
    `export type DateString = string & { readonly __date: unique symbol };`,
    `export type MarkdownString = string & { readonly __markdown: unique symbol };`,
    ''
  );

  lines.push(
    `export interface Entry<F> {`,
    `  /** Stable 32-char hex id (UUIDv7). */`,
    `  id: string;`,
    `  type: string;`,
    `  slug: string;`,
    `  version: number;`,
    `  published_version?: number;`,
    `  fields: F;`,
    `  tags?: { slug: string; label: string }[];`,
    `}`,
    ''
  );

  // Per-type interfaces, sorted alphabetically by type name for stable output.
  const typeNames = Object.keys(model.types).sort();
  for (const name of typeNames) {
    const t = model.types[name]!;
    lines.push(...emitTypeInterface(name, t));
    lines.push('');
  }

  // Entries map — type-name string → interface.
  lines.push(`export interface Entries {`);
  for (const name of typeNames) {
    lines.push(`  ${quoteIfNeeded(name)}: ${pascal(name)};`);
  }
  lines.push(`}`, '');

  if (opts.augmentSdk) {
    lines.push(
      `declare module '@ledric/sdk' {`,
      `  interface LedricEntries extends Entries {}`,
      `}`,
      ''
    );
  }

  return lines.join('\n');
}

function emitTypeInterface(name: string, t: TypeDescription): string[] {
  const interfaceName = pascal(name);
  const lines: string[] = [];
  if (t.description) {
    lines.push(`/** ${t.description.replace(/\*\//g, '*\\/')} */`);
  }
  lines.push(`export interface ${interfaceName} {`);
  const fieldEntries = Object.entries(t.fields ?? {});
  if (fieldEntries.length === 0) {
    lines.push(`  [k: string]: unknown;`);
  } else {
    for (const [fieldName, def] of fieldEntries) {
      const opt = def.required === true ? '' : '?';
      const tsType = fieldDefToTs(def, 1);
      const safeName = quoteIfNeeded(fieldName);
      // Inline single-line field comment when description is present.
      const desc = (def as FieldDef & { description?: string }).description;
      if (desc) {
        lines.push(`  /** ${desc.replace(/\*\//g, '*\\/')} */`);
      }
      lines.push(`  ${safeName}${opt}: ${tsType};`);
    }
  }
  lines.push(`}`);
  return lines;
}

function fieldDefToTs(def: FieldDef, depth: number): string {
  // Localized fields are still typed as their base type — the _locale
  // sidecar carries overrides separately on the entry envelope.
  switch (def.type) {
    case 'string':
    case 'slug':
    case 'css':
      return 'string';
    case 'number':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'date':
      return 'DateString';
    case 'markdown':
      return 'MarkdownString';
    case 'asset':
      return 'AssetId';
    case 'enum': {
      const values = ((def as FieldDef & { values?: readonly string[] }).values ?? []).map(
        (v) => JSON.stringify(v)
      );
      return values.length > 0 ? values.join(' | ') : 'string';
    }
    case 'references': {
      const tos = ((def as FieldDef & { to?: readonly string[] }).to ?? []).map(
        (t) => `'${t}'`
      );
      return tos.length > 0 ? `EntryRef<${tos.join(' | ')}>[]` : 'EntryRef[]';
    }
    case 'array': {
      const ofDef = (def as FieldDef & { of?: FieldDef }).of;
      if (!ofDef) return 'unknown[]';
      // Wrap unions in parens so `(A | B)[]` parses correctly.
      const inner = fieldDefToTs(ofDef, depth);
      const needsParens = /\s\|\s/.test(inner);
      return needsParens ? `(${inner})[]` : `${inner}[]`;
    }
    case 'object': {
      const objFields = (def as FieldDef & { fields?: Record<string, FieldDef> }).fields ?? {};
      const entries = Object.entries(objFields);
      if (entries.length === 0) return 'Record<string, unknown>';
      const indent = '  '.repeat(depth + 1);
      const closeIndent = '  '.repeat(depth);
      const body = entries
        .map(([n, f]) => {
          const opt = f.required === true ? '' : '?';
          return `${indent}${quoteIfNeeded(n)}${opt}: ${fieldDefToTs(f, depth + 1)};`;
        })
        .join('\n');
      return `{\n${body}\n${closeIndent}}`;
    }
    case 'jss':
      return 'Record<string, unknown>';
    case 'vector':
      return 'number[]';
    default:
      return 'unknown';
  }
}

function pascal(name: string): string {
  return name
    .split(/[_-]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

const VALID_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
function quoteIfNeeded(name: string): string {
  return VALID_IDENT.test(name) ? name : JSON.stringify(name);
}
